remote_ theme: pages-themes/cayman@v0.2.0
.tabs {
  width: 100%;
  display: inline-block;
}
 
.tab-list {
  padding: 0;
  margin: 0;
  list-style: none;
}
 
.tab-item {
  display: inline-block;
  margin-right: 10px;
  padding: 10px;
  cursor: pointer;
  background-color: #f1f1f1;
  border-radius: 5px 5px 0 0;
}
 
.tab-item.active {
  background-color: #fff;
}
 
.tab-content {
  border: 1px solid #f1f1f1;
  padding: 20px;
  border-radius: 5px;
}
 
.tab-pane {
  display: none;
}
 
.tab-pane.active {
  display: block;
}
